apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-cm
data:
  datasource.yml: |
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prom-service:9090
        isDefault: true
        access: proxy
        editable: true
  dashboard.yaml: |
      apiVersion: 1
      providers:
        - name: "Dashboard provider"
          orgId: 1
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: false
          options:
            path: /var/lib/grafana/dashboards
            foldersFromFilesStructure: true
