apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana
    spec:
      volumes:
      - name: grafana-cm
        configMap:
          name: {{ .Release.Name }}-grafana-cm
      - name: grafana-pv-storage
        persistentVolumeClaim:
          claimName: grafana-pv-claim
      containers:
      - image: grafana/grafana:latest
        name: grafana
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        tty: true
        stdin: true
        volumeMounts:
          - mountPath: /etc/grafana/provisioning/datasources/datasource.yml
            name: grafana-cm
            subPath: datasource.yml
          - mountPath: /etc/grafana/provisioning/dashboards/main.yaml
            name: grafana-cm
            subPath: dashboard.yaml
          - mountPath: "/var/lib/grafana/dashboards"
            name: grafana-pv-storage
