apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grafana-service
  labels:
    app: {{ .Release.Name }}-grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: tcp-3000
  selector:
    app: {{ .Release.Name }}-grafana
  type: "ClusterIP"

