apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-prom-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: my-prom.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prom-service
                port:
                  number: 9090
          - path: /alertmanager 
            pathType: Prefix
            backend:
              service:
                name: alertmanager
                port:
                  number: 9093
          - path: /metrics 
            pathType: Prefix
            backend:
              service:
                name: metrics
                port:
                  number: 9100
