apiVersion: v1
kind: Service
metadata:
  name: prom-service
  labels:
    app: {{ .Release.Name }}-prom
spec:
spec:
  ports:
  - name: prom-service
    port: 9090
#    protocol: TCP
#    targetPort: prom-service
  - name: alertmanager
    port: 9093
#    protocol: TCP    
#    targetPort: alertmanager
  - name: metrics
    port: 9100
  selector:
    app: {{ .Release.Name }}-prom
  type: "ClusterIP"
